import { ConfigService } from "@nestjs/config";
import { generateKeyPairSync } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { Environment } from "../src/config/environment";
import { GitHubAppService } from "../src/connectors/github-app.service";

describe("GitHubAppService", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("accepts the PKCS#1 private key format generated by GitHub", async () => {
    const { privateKey } = generateKeyPairSync("rsa", {
      modulusLength: 2048,
      privateKeyEncoding: {
        format: "pem",
        type: "pkcs1",
      },
      publicKeyEncoding: {
        format: "pem",
        type: "spki",
      },
    });
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(
        JSON.stringify({
          id: 456,
          account: { id: 1, login: "atlas", type: "User" },
          repository_selection: "selected",
          permissions: { contents: "read" },
        }),
        {
          headers: { "Content-Type": "application/json" },
          status: 200,
        },
      ),
    );
    vi.stubGlobal("fetch", fetchMock);

    const config = new ConfigService<Environment>({
      GITHUB_APP_ID: "123",
      GITHUB_APP_PRIVATE_KEY: Buffer.from(privateKey).toString("base64"),
    });
    const service = new GitHubAppService(
      config as unknown as ConfigService<Environment, true>,
    );

    await expect(service.getInstallation("456")).resolves.toMatchObject({
      id: 456,
    });
    expect(fetchMock).toHaveBeenCalledWith(
      "https://api.github.com/app/installations/456",
      expect.objectContaining({
        headers: expect.objectContaining({
          Authorization: expect.stringMatching(/^Bearer ey/),
        }),
      }),
    );
  });
});
