import { ConfigService } from "@nestjs/config";
import { generateKeyPairSync } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { Environment } from "../src/config/environment";
import { GitHubAppService } from "../src/connectors/github-app.service";

function githubService() {
  const { privateKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    privateKeyEncoding: {
      format: "pem",
      type: "pkcs1",
    },
    publicKeyEncoding: {
      format: "pem",
      type: "spki",
    },
  });
  const config = new ConfigService<Environment>({
    GITHUB_APP_ID: "123",
    GITHUB_APP_PRIVATE_KEY: Buffer.from(privateKey).toString("base64"),
  });
  return new GitHubAppService(
    config as unknown as ConfigService<Environment, true>,
  );
}

function commitResponse(index: number) {
  return {
    sha: `sha-${index}`,
    html_url: `https://github.com/atlas/web/commit/sha-${index}`,
    commit: {
      message: `Commit ${index}`,
      author: {
        name: "Atlas Engineer",
        date: "2026-08-01T00:00:00.000Z",
      },
      committer: { date: "2026-08-01T00:01:00.000Z" },
    },
    author: { login: "atlas-engineer" },
    parents: [{ sha: `parent-${index}` }],
  };
}

describe("GitHubAppService", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("accepts the PKCS#1 private key format generated by GitHub", async () => {
    const { privateKey } = generateKeyPairSync("rsa", {
      modulusLength: 2048,
      privateKeyEncoding: {
        format: "pem",
        type: "pkcs1",
      },
      publicKeyEncoding: {
        format: "pem",
        type: "spki",
      },
    });
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response(
        JSON.stringify({
          id: 456,
          account: { id: 1, login: "atlas", type: "User" },
          repository_selection: "selected",
          permissions: { contents: "read" },
        }),
        {
          headers: { "Content-Type": "application/json" },
          status: 200,
        },
      ),
    );
    vi.stubGlobal("fetch", fetchMock);

    const config = new ConfigService<Environment>({
      GITHUB_APP_ID: "123",
      GITHUB_APP_PRIVATE_KEY: Buffer.from(privateKey).toString("base64"),
    });
    const service = new GitHubAppService(
      config as unknown as ConfigService<Environment, true>,
    );

    await expect(service.getInstallation("456")).resolves.toMatchObject({
      id: 456,
    });
    const [url, init] = fetchMock.mock.calls[0] ?? [];
    expect(url).toBe("https://api.github.com/app/installations/456");
    expect(new Headers(init?.headers).get("Authorization")).toMatch(
      /^Bearer ey/,
    );
  });

  it("paginates pull-request files beyond the first 100", async () => {
    const { privateKey } = generateKeyPairSync("rsa", {
      modulusLength: 2048,
      privateKeyEncoding: {
        format: "pem",
        type: "pkcs1",
      },
      publicKeyEncoding: {
        format: "pem",
        type: "spki",
      },
    });
    const files = Array.from({ length: 125 }, (_, index) => ({
      filename: `src/file-${index}.ts`,
      status: "modified",
      additions: 1,
      deletions: 1,
      changes: 2,
    }));
    const fetchMock = vi.fn<typeof fetch>(async (request) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      if (url.endsWith("/repos/atlas/web/pulls/42")) {
        return new Response(
          JSON.stringify({
            number: 42,
            title: "Large change",
            body: null,
            html_url: "https://github.com/atlas/web/pull/42",
            changed_files: 125,
            additions: 125,
            deletions: 125,
            user: { login: "engineer" },
            base: { sha: "base", ref: "main" },
            head: { sha: "head", ref: "feature" },
          }),
          { headers: { "Content-Type": "application/json" }, status: 200 },
        );
      }
      if (url.includes("/pulls/42/reviews")) {
        return new Response(JSON.stringify([]), {
          headers: { "Content-Type": "application/json" },
          status: 200,
        });
      }
      const page = new URL(url).searchParams.get("page");
      return new Response(
        JSON.stringify(page === "1" ? files.slice(0, 100) : files.slice(100)),
        { headers: { "Content-Type": "application/json" }, status: 200 },
      );
    });
    vi.stubGlobal("fetch", fetchMock);
    const config = new ConfigService<Environment>({
      GITHUB_APP_ID: "123",
      GITHUB_APP_PRIVATE_KEY: Buffer.from(privateKey).toString("base64"),
    });
    const service = new GitHubAppService(
      config as unknown as ConfigService<Environment, true>,
    );

    const result = await service.getPullRequest("456", "atlas", "web", 42);

    expect(result.files).toHaveLength(125);
    expect(result.filesTruncated).toBe(false);
    expect(
      fetchMock.mock.calls.some(([request]) => {
        const url =
          request instanceof Request ? request.url : request.toString();
        return url.includes("per_page=100&page=2");
      }),
    ).toBe(true);
  });

  it("retrieves bounded recent pull-request provenance in one GraphQL request", async () => {
    const fetchMock = vi.fn<typeof fetch>(async (request, init) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      const body = JSON.parse(init?.body as string) as {
        query: string;
        variables: Record<string, string>;
      };
      expect(url).toBe("https://api.github.com/graphql");
      expect(body.query).toContain("pullRequests(first: 50");
      expect(body.query).toContain("reviews(last: 50)");
      expect(body.query.match(/\.\.\. on Node \{ id \}/g)).toHaveLength(3);
      expect(body.query).not.toMatch(/author \{ id /);
      expect(body.query).not.toMatch(/mergedBy \{ id /);
      expect(body.variables).toEqual({ owner: "atlas", repository: "web" });
      return new Response(
        JSON.stringify({
          data: {
            repository: {
              pullRequests: {
                nodes: [
                  {
                    id: "PR_node",
                    number: 42,
                    title: "Add provenance",
                    url: "https://github.com/atlas/web/pull/42",
                    state: "MERGED",
                    isDraft: false,
                    author: {
                      id: "U_author",
                      login: "engineer",
                      name: "Atlas Engineer",
                      avatarUrl: "https://avatars.githubusercontent.com/u/1",
                      url: "https://github.com/engineer",
                      __typename: "User",
                    },
                    mergedBy: null,
                    baseRefOid: "base",
                    headRefOid: "head",
                    createdAt: "2026-08-01T00:00:00.000Z",
                    updatedAt: "2026-08-02T00:00:00.000Z",
                    closedAt: "2026-08-02T00:00:00.000Z",
                    mergedAt: "2026-08-02T00:00:00.000Z",
                    reviews: {
                      nodes: [
                        {
                          id: "R_review",
                          author: {
                            id: "B_bot",
                            login: "review-bot",
                            avatarUrl: "https://avatars.githubusercontent.com/u/2",
                            url: "https://github.com/apps/review-bot",
                            __typename: "Bot",
                          },
                          state: "APPROVED",
                          submittedAt: "2026-08-01T12:00:00.000Z",
                          url: "https://github.com/atlas/web/pull/42#pullrequestreview-1",
                        },
                      ],
                      pageInfo: { hasPreviousPage: true },
                    },
                  },
                ],
              },
            },
          },
        }),
        { headers: { "Content-Type": "application/json" }, status: 200 },
      );
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await githubService().getRecentPullRequestProvenance({
      installationId: "456",
      owner: "atlas",
      repository: "web",
    });

    expect(result).toHaveLength(1);
    expect(result[0]).toMatchObject({
      providerPullRequestId: "PR_node",
      number: 42,
      mergedBy: null,
      reviewsTruncated: true,
    });
    expect(result[0]?.author).toMatchObject({
      login: "engineer",
      displayName: "Atlas Engineer",
      kind: "person",
    });
    expect(result[0]?.reviews[0]).toMatchObject({
      providerReviewId: "R_review",
      state: "APPROVED",
    });
    expect(result[0]?.reviews[0]?.reviewer?.kind).toBe("bot");
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it("captures on-demand review actors and unavailable identities", async () => {
    const fetchMock = vi.fn<typeof fetch>(async (request) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      if (url.endsWith("/repos/atlas/web/pulls/42")) {
        return new Response(
          JSON.stringify({
            number: 42,
            title: "Review provenance",
            body: null,
            html_url: "https://github.com/atlas/web/pull/42",
            changed_files: 0,
            additions: 0,
            deletions: 0,
            user: null,
            base: { sha: "base", ref: "main" },
            head: { sha: "head", ref: "feature" },
          }),
          { headers: { "Content-Type": "application/json" }, status: 200 },
        );
      }
      if (url.includes("/pulls/42/files")) {
        return new Response(JSON.stringify([]), {
          headers: { "Content-Type": "application/json" },
          status: 200,
        });
      }
      return new Response(
        JSON.stringify([
          {
            id: 8,
            node_id: "R_8",
            user: null,
            state: "COMMENTED",
            submitted_at: "2026-08-03T00:00:00.000Z",
            html_url: "https://github.com/atlas/web/pull/42#pullrequestreview-8",
          },
        ]),
        { headers: { "Content-Type": "application/json" }, status: 200 },
      );
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await githubService().getPullRequest(
      "456",
      "atlas",
      "web",
      42,
    );

    expect(result.reviews).toEqual([
      expect.objectContaining({
        providerReviewId: "R_8",
        reviewer: null,
        state: "COMMENTED",
      }),
    ]);
    expect(result.reviewsTruncated).toBe(false);
  });

  it("captures a bounded three-page comparison with aggregate file changes", async () => {
    const commits = Array.from({ length: 300 }, (_, index) =>
      commitResponse(index),
    );
    const files = Array.from({ length: 305 }, (_, index) => ({
      filename: `src/file-${index}.ts`,
      status: "modified",
      additions: 1,
      deletions: 1,
      changes: 2,
    }));
    const fetchMock = vi.fn<typeof fetch>(async (request) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      const page = Number(new URL(url).searchParams.get("page"));
      const offset = (page - 1) * 100;
      return new Response(
        JSON.stringify({
          status: "ahead",
          ahead_by: 350,
          behind_by: 0,
          total_commits: 350,
          commits: commits.slice(offset, offset + 100),
          files: page === 1 ? files : undefined,
        }),
        { headers: { "Content-Type": "application/json" }, status: 200 },
      );
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await githubService().getRepositoryHistory({
      installationId: "456",
      owner: "atlas",
      repository: "web",
      baseRevision: "base-sha",
      headRevision: "head-sha",
    });

    expect(result).toMatchObject({
      baseRevision: "base-sha",
      headRevision: "head-sha",
      status: "ahead",
      aheadBy: 350,
      totalCommits: 350,
      commitsTruncated: true,
      filesTruncated: true,
    });
    expect(result.commits).toHaveLength(300);
    expect(result.files).toHaveLength(300);
    expect(result.commits[0]).toMatchObject({
      sha: "sha-0",
      authorLogin: "atlas-engineer",
      parentShas: ["parent-0"],
    });
    expect(
      fetchMock.mock.calls.filter(([request]) => {
        const url =
          request instanceof Request ? request.url : request.toString();
        return url.includes("/compare/");
      }),
    ).toHaveLength(3);
  });

  it("falls back to bounded recent commits when a revision comparison is unavailable", async () => {
    const recentCommits = [commitResponse(1), commitResponse(2)];
    const fetchMock = vi.fn<typeof fetch>(async (request) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      if (url.includes("/compare/")) {
        return new Response(JSON.stringify({ message: "Not Found" }), {
          headers: { "Content-Type": "application/json" },
          status: 404,
        });
      }
      return new Response(JSON.stringify(recentCommits), {
        headers: { "Content-Type": "application/json" },
        status: 200,
      });
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await githubService().getRepositoryHistory({
      installationId: "456",
      owner: "atlas",
      repository: "web",
      baseRevision: "deleted-base",
      headRevision: "head-sha",
    });

    expect(result).toMatchObject({
      baseRevision: "deleted-base",
      headRevision: "head-sha",
      status: "comparison_unavailable",
      aheadBy: 2,
      totalCommits: 2,
      commitsTruncated: false,
      files: [],
    });
    expect(result.commits.map((commit) => commit.sha)).toEqual([
      "sha-1",
      "sha-2",
    ]);
  });

  it("uses recent history directly for a repository's initial synchronization", async () => {
    const fetchMock = vi.fn<typeof fetch>(async (request) => {
      const url =
        request instanceof Request ? request.url : request.toString();
      if (url.endsWith("/app/installations/456/access_tokens")) {
        return new Response(JSON.stringify({ token: "installation-token" }), {
          headers: { "Content-Type": "application/json" },
          status: 201,
        });
      }
      return new Response(JSON.stringify([commitResponse(1)]), {
        headers: { "Content-Type": "application/json" },
        status: 200,
      });
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await githubService().getRepositoryHistory({
      installationId: "456",
      owner: "atlas",
      repository: "web",
      headRevision: "head-sha",
    });

    expect(result).toMatchObject({
      baseRevision: null,
      headRevision: "head-sha",
      status: "recent",
      commitsTruncated: false,
    });
    expect(
      fetchMock.mock.calls.some(([request]) => {
        const url =
          request instanceof Request ? request.url : request.toString();
        return url.includes("/compare/");
      }),
    ).toBe(false);
  });
});
