"use client";

import { useState } from "react";
import { Bell, Check, ChevronDown, Database, Filter, GitBranch, Network, Plus, RefreshCw, Search, Settings, ShieldCheck, Users } from "lucide-react";
import { ConfidenceBadge } from "@/components/brand";
import { PageHeader, StatusDot } from "@/components/app/shared";
import { activity, repositories } from "@/lib/mock-data";

export function SourcesPage() {
  const [githubConnected, setGithubConnected] = useState(true);
  const [notionConnected, setNotionConnected] = useState(true);
  return (
    <>
      <PageHeader eyebrow="Connected context" title="Sources" detail="Control what Atlas can index and see the freshness of every engineering source." action={<button className="button button--primary"><Plus size={15} /> Connect source</button>} />
      <div className="connector-grid"><article className="connector-card"><div className="connector-top"><i><GitBranch size={22} /></i><ConfidenceBadge type="observed" /></div><h2>GitHub</h2><p>Code, pull requests, commits, authors, and reviews from Northstar Labs.</p><div className="connector-stats"><div><b>12</b><span>repositories</span></div><div><b>1.4k</b><span>pull requests</span></div><div><b>4m</b><span>last sync</span></div></div><div className="connector-footer"><label><input type="checkbox" checked={githubConnected} onChange={(event) => setGithubConnected(event.target.checked)} /><span /></label><b>{githubConnected ? "Connected" : "Paused"}</b><button>Manage</button></div></article><article className="connector-card"><div className="connector-top"><i className="notion-icon">N</i><ConfidenceBadge type="observed" /></div><h2>Notion</h2><p>Architecture decisions, runbooks, and technical design documents.</p><div className="connector-stats"><div><b>86</b><span>pages</span></div><div><b>6</b><span>databases</span></div><div><b>12m</b><span>last sync</span></div></div><div className="connector-footer"><label><input type="checkbox" checked={notionConnected} onChange={(event) => setNotionConnected(event.target.checked)} /><span /></label><b>{notionConnected ? "Connected" : "Paused"}</b><button>Manage</button></div></article><article className="connector-card connector-card--add"><Plus size={23} /><h2>Add another source</h2><p>Operational context is coming after the Atlas pilot.</p><button className="button button--ghost">View roadmap</button></article></div>
      <section className="panel repository-table"><div className="panel-heading"><div><span>GitHub repositories</span><h2>Index coverage</h2></div><div className="search-input search-input--small"><Search size={14} /><input placeholder="Filter repositories" /></div></div><div className="table-head"><span>Repository</span><span>Language</span><span>Files</span><span>Status</span><span>Updated</span></div>{repositories.map((repo) => <div className="table-row" key={repo.name}><span><GitBranch size={15} /><b>{repo.name}</b></span><span>{repo.language}</span><span>{repo.files}</span><span><StatusDot state={repo.status === "Syncing" ? "running" : "ready"} /> {repo.status}</span><span>{repo.updated}</span></div>)}</section>
    </>
  );
}

export function ActivityPage() {
  return <><PageHeader eyebrow="Repository intelligence" title="Sync activity" detail="Watch Atlas transform engineering sources into structured, searchable context." action={<button className="button button--primary"><RefreshCw size={15} /> Sync all</button>} /><div className="activity-grid"><section className="panel active-sync"><div className="panel-heading"><div><span>Currently indexing</span><h2>billing-service</h2></div><span className="running-badge"><RefreshCw className="spin" size={13} /> Running</span></div><div className="sync-progress"><div><span>Resolving symbols and imports</span><b>68%</b></div><div className="progress-track"><i style={{ width: "68%" }} /></div><p>438 of 719 files · 24 seconds elapsed</p></div><div className="sync-stages">{["Download source", "Parse project", "Resolve graph", "Create embeddings", "Publish index"].map((step, index) => <div className={index < 2 ? "done" : index === 2 ? "current" : ""} key={step}><i>{index < 2 ? <Check size={12} /> : index + 1}</i><span>{step}</span></div>)}</div></section><section className="panel activity-stats"><div><span>Successful syncs</span><strong>284</strong><p>99.3% this month</p></div><div><span>Median duration</span><strong>42s</strong><p>−8s from last week</p></div><div><span>Graph changes</span><strong>241</strong><p>this week</p></div></section></div><section className="panel activity-log"><div className="panel-heading"><div><span>Workspace events</span><h2>Recent activity</h2></div><button className="button button--ghost"><Filter size={14} /> Filter</button></div><div className="timeline">{[...activity, { time: "Yesterday", title: "Repository disconnected", detail: "legacy-auth-proxy · data removed", state: "done" }, { time: "Yesterday", title: "GitHub permissions updated", detail: "2 repositories added by Priyansh", state: "done" }].map((item) => <div key={`${item.time}-${item.title}`}><StatusDot state={item.state === "running" ? "running" : "ready"} /><span>{item.time}</span><p><b>{item.title}</b><small>{item.detail}</small></p><button>Details</button></div>)}</div></section></>;
}

export function SettingsPage() {
  const [section, setSection] = useState("Workspace");
  return <><PageHeader eyebrow="Workspace administration" title="Settings" detail="Manage Northstar Labs, its members, access, and Atlas preferences." /><div className="settings-layout"><aside>{["Workspace", "Members", "Access & roles", "Notifications", "Data & privacy"].map((item) => <button className={section === item ? "active" : ""} onClick={() => setSection(item)} key={item}>{item === "Members" ? <Users size={15} /> : item === "Access & roles" ? <ShieldCheck size={15} /> : item === "Notifications" ? <Bell size={15} /> : item === "Data & privacy" ? <Database size={15} /> : <Settings size={15} />}{item}</button>)}</aside><main className="panel settings-panel"><span>General</span><h2>{section}</h2><p>Configure how this Atlas workspace appears to your engineering team.</p><div className="settings-form"><label className="field"><span>Workspace name</span><input defaultValue="Northstar Labs" /></label><label className="field"><span>Workspace slug</span><div className="prefix-input"><span>atlas.dev/</span><input defaultValue="northstar" /></div></label><label className="field"><span>Default analysis scope</span><button className="select-like"><Network size={15} /> Entire workspace <ChevronDown size={15} /></button></label><div className="setting-toggle"><div><b>Show inferred relationships</b><p>Include low-confidence semantic relationships in graph views.</p></div><label><input type="checkbox" defaultChecked /><span /></label></div><div className="setting-toggle"><div><b>Weekly intelligence digest</b><p>Send architecture and knowledge changes every Monday.</p></div><label><input type="checkbox" defaultChecked /><span /></label></div></div><div className="settings-actions"><button className="button button--primary">Save changes</button></div></main></div></>;
}
